### ISSUE TITLE
Hello! Is there any intention to do field verification?

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#3]
Hello! Is there any intention to do field verification?
Similar to this！

```
type User {
	email: String  @validator(required: "true", tye: "email")
	firstName: String
	lastName: String
}
```

**Comment by jakubknejzlik** [comment]
Hi @maiguangyang, this should be relatively easy to implement. Currently we do the validation by overriding the resolver, but you can also register your own directives (that's why we didn't plan to add any custom directives by default):
https://gqlgen.com/reference/directives/

I can update the example to show how to accomplish it.

**Comment by maiguangyang** [comment]
Then trouble to update the example, thank you very much!
Your project is very well written.

**Comment by jakubknejzlik** [comment]
Thanks :-)
Hmmm...you are correct, that it's not that easy to put custom directive to validate input. The directive isn't propagated to entity update/create input types.

I'm not sure if we want to implement specific directives rather than provide way how to add to specific fields (something like "directive to define directive"). We also plan to add support for defining custom fields in schema definition (query/mutation) so the process would be more about merging generated and defined schema...this would may be also another option, eg.:

```
directive @validator(type: String!) on FIELD_DEFINITION

type CompanyCreateInput {
  email: String! @validator(type:"email")
  # rest of properties will be filled by generator
}
type CompanyUpdateInput {
  email: String @validator(type:"email")
  # rest of properties will be filled by generator
}

type Company {
  email: String!
  name: String
  street: String
  city: String
}
```
...currently this seems to me as the most transparent way without any special magic. The only thing I'm little bit worried is the fact, that you have to keep the naming pattern `{ENTITY_NAME}CreateInput` and `{ENTITY_NAME}UpdateInput` which may be more error prone (especially in case when you want to override query/mutation fields)

Please also note, that you can specify required field by adding `!` after field type (non-optional). This will end up requiring the field for creating and marking it optional for updates.

**Comment by jakubknejzlik** [comment]
Hello @maiguangyang, once resolver handlers has been added it's now easy to implement custom validation (although not using the custom directives). Please check this method to see how you can override the default handler to add field validation (on user creation):
https://github.com/novacloudcz/graphql-orm-example/blob/master/src/resolver.go#L16

I'm closing this issue, but feel free to reopen it if needed.

FYI: I've created issue #21 to track the progress of directive usage for handling validation.
