### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by frederikhors** [novacloudcz/graphql-orm#67]
Hi @jakubknejzlik,

I have nothing interesting to write because I discovered your project a little while ago.

It dazzled me!

**CONGRATULATIONS!** REALLY!

It is one of the most beautiful Go projects I discovered in recent months.

Please continue! **Do not stop!**

And thank you for what you teach the world.

**Comment by jakubknejzlik** [comment]
Hello @frederikhors , thanks for Your feedback. To be honest I don't have as much time as I'd like to support this project nowadays. That's why for example there's still no support for latest gorm version. But thanks for motivation :-) 

There's also bunch of other projects with pretty large community as well...have You for example tried Prisma (https://github.com/prisma/prisma)? It's not in golang, but looks really interesting (especially since they switched from scala to typescript).

**Comment by frederikhors** [comment]
> There's also bunch of other projects with pretty large community as well...

I love Golang only.
